input {
  file {
    path => "/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  csv {
    separator => ","
    columns => ["id","title","genres","original_language","overview",
                "popularity","production_companies","release_date",
                "budget","revenue","runtime","status","tagline",
                "vote_average","vote_count","credits","keywords",
                "poster_path","backdrop_path","recommendations"]
  }

  if [id] == "id" { drop {} }

  mutate {
    convert => {
      "popularity"   => "float"
      "budget"       => "integer"
      "revenue"      => "integer"
      "runtime"      => "integer"
      "vote_average" => "float"
      "vote_count"   => "integer"
    }
  }

  date {
    match => ["release_date", "yyyy-MM-dd"]
    target => "release_date"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_raw"
    document_id => "%{id}"
  }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_clean"
    document_id => "%{id}"
  }
}